#!/usr/bin/env python
"""Generate new_chapters/appendix.tex.

Everything is derived from the recorded run rather than transcribed, so the
appendix cannot drift from Chapter 4. Per-fold precision, recall and F1 are
recomputed from the stored per-fold confusion matrices, and the result is
checked against the aggregate values in results.json before anything is
written.

    python -m scripts.make_appendix
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

from scripts.constants import PROJECT_ROOT

RES = PROJECT_ROOT / "outputs" / "rerun_full_library" / "results.json"
CONFIG = PROJECT_ROOT / "config" / "default_new.yaml"
ENV = PROJECT_ROOT / "environment.yml"
OUT = PROJECT_ROOT / "new_chapters" / "appendix.tex"

LABEL = {"lstm": "Bidirectional LSTM", "cnn_lstm": "CNN-LSTM",
         "transformer": "Transformer encoder"}
SHORT = {"lstm": "lstm", "cnn_lstm": "cnn\\_lstm", "transformer": "transformer"}
CLASSES = ["Background", "Crack", "Noise"]


def per_class(cm: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Precision, recall, F1 per class; a score is zero when its denominator is,
    matching scripts/cross_validation.py."""
    tp = np.diag(cm).astype(float)
    pred, true = cm.sum(axis=0).astype(float), cm.sum(axis=1).astype(float)
    with np.errstate(divide="ignore", invalid="ignore"):
        p = np.where(pred > 0, tp / np.where(pred > 0, pred, 1), 0.0)
        r = np.where(true > 0, tp / np.where(true > 0, true, 1), 0.0)
        f = np.where(p + r > 0, 2 * p * r / np.where(p + r > 0, p + r, 1), 0.0)
    return p, r, f


def main() -> None:
    res = json.loads(RES.read_text())
    models = res["models"]

    # --- self-check: recomputed per-fold values must reproduce the aggregates ---
    for key, m in models.items():
        pf = np.array([per_class(np.array(cm)) for cm in m["per_fold_cm"]])  # (5,3,3)
        for i, name in enumerate(("precision", "recall", "f1")):
            got, want = pf[:, i, :].mean(axis=0), np.array(m[f"{name}_mean"])
            assert np.allclose(got, want, atol=5e-4), (key, name, got, want)
    print("self-check passed: per-fold values reproduce the aggregates in results.json")

    L: list[str] = []
    w = L.append

    w("% Generated by scripts/make_appendix.py -- do not edit by hand.")
    w("% Regenerate after any rerun so the numbers stay tied to results.json.")
    w("")
    w("\\appendix")
    w("")
    w("\\chapter{Per-Fold Confusion Matrices}")
    w("\\label{app:per-fold-cm}")
    w("")
    w("Chapter~\\ref{ch:results} reports the confusion matrix of each model summed "
      "over the five cross-validation folds. The individual fold matrices are given "
      "here. Each figure shows frame counts on the left and the same matrix "
      "normalised by row on the right, so that each row shows how the frames of one "
      "true class were distributed across the predicted classes. All matrices come "
      "from the training-seed-0 run reported in Chapter~\\ref{ch:results}.")
    w("")
    for key in ("lstm", "cnn_lstm", "transformer"):
        w(f"\\section{{{LABEL[key]}}}")
        w(f"\\label{{app:cm-{key.replace('_', '-')}}}")
        w("")
        for fold in range(1, 6):
            w("\\begin{figure}[htbp]")
            w("\\centering")
            w(f"\\includegraphics[width=0.92\\textwidth]"
              f"{{ch4_confusion_{key}_fold{fold}.png}}")
            w(f"\\caption{{{LABEL[key]}, cross-validation fold {fold}: frame counts "
              f"(left) and row-normalised (right).}}")
            w(f"\\label{{fig:app-cm-{key.replace('_', '-')}-f{fold}}}")
            w("\\end{figure}")
            w("")
        w("\\clearpage")
        w("")

    w("\\chapter{Per-Fold Numerical Results}")
    w("\\label{app:per-fold-numbers}")
    w("")
    w("Chapter~\\ref{ch:results} reports per-class scores as a mean and standard "
      "deviation across the five folds. The underlying per-fold values are given "
      "here, recomputed from the fold confusion matrices of "
      "Appendix~\\ref{app:per-fold-cm}. A score is defined as zero when its "
      "denominator is zero. The final row of each table repeats the mean and "
      "standard deviation as reported in Chapter~\\ref{ch:results}.")
    w("")

    for key in ("lstm", "cnn_lstm", "transformer"):
        m = models[key]
        w(f"\\section{{{LABEL[key]}}}")
        w("")
        w("\\begin{table}[htbp]")
        w("\\centering")
        w(f"\\caption[{LABEL[key]}: per-fold results]{{{LABEL[key]}: per-class precision, recall and F1 in each "
          f"cross-validation fold, with macro F1 and accuracy.}}")
        w(f"\\label{{tab:app-folds-{key.replace('_', '-')}}}")
        w("\\footnotesize")
        w("\\setlength{\\tabcolsep}{4pt}")
        w("\\begin{tabularx}{\\textwidth}{|l|*{11}{>{\\centering\\arraybackslash}X|}}")
        w("\\hline")
        w(" & \\multicolumn{3}{c|}{Background} & \\multicolumn{3}{c|}{Crack}"
          " & \\multicolumn{3}{c|}{Noise} & & \\\\")
        w("\\cline{2-4}\\cline{5-7}\\cline{8-10}")
        w("Fold & P & R & F1 & P & R & F1 & P & R & F1 & Macro F1 & Acc. \\\\")
        w("\\hline")
        for i, cm in enumerate(m["per_fold_cm"]):
            p, r, f = per_class(np.array(cm))
            cells = " & ".join(f"{v:.3f}" for c in range(3)
                               for v in (p[c], r[c], f[c]))
            w(f"{i + 1} & {cells} & {m['macro_f1_per_fold'][i]:.3f}"
              f" & {m['accuracy_per_fold'][i]:.3f} \\\\")
        w("\\hline")
        mean = " & ".join(f"{v:.3f}" for c in range(3)
                          for v in (m["precision_mean"][c], m["recall_mean"][c],
                                    m["f1_mean"][c]))
        sd = " & ".join(f"{v:.3f}" for c in range(3)
                        for v in (m["precision_std"][c], m["recall_std"][c],
                                  m["f1_std"][c]))
        w(f"Mean & {mean} & {m['macro_f1_mean']:.3f}"
          f" & {np.mean(m['accuracy_per_fold']):.3f} \\\\")
        w(f"SD & {sd} & {m['macro_f1_std']:.3f}"
          f" & {np.std(m['accuracy_per_fold'], ddof=1):.3f} \\\\")
        w("\\hline")
        w("\\end{tabularx}")
        w("\\vspace{2pt}")
        w(f"\\par{{\\footnotesize Training and validation chunks per fold: "
          f"{', '.join(f'{a}/{b}' for a, b in zip(m['n_train_per_fold'], m['n_val_per_fold']))}.}}")
        w("\\end{table}")
        w("")

    w("\\clearpage")
    w("")
    w("\\chapter{Configuration and Software Environment}")
    w("\\label{app:config}")
    w("")
    w("\\section{Pipeline configuration}")
    w("")
    w("{\\sloppy The configuration file below is the file used for all results reported in this thesis. "
      "It contains the data, spectrogram, LSTM and training settings described in "
      "Chapter~\\ref{ch:data-setup}. The settings that are not part of it are fixed in the code: "
      "the CNN-LSTM channels (32, 64, 128) and kernel size (3$\\times$3) and the Transformer "
      "heads (8), feed-forward size (256) and layers (2) are the defaults in "
      "\\texttt{models/cnn\\_lstm.py} and \\texttt{models/transformer.py}, passed through "
      "\\texttt{MODEL\\_CFGS} in \\texttt{scripts/augmentation\\_experiment.py}; the five "
      "cross-validation folds come from \\texttt{k=5} in the calls to "
      "\\texttt{stratified\\_kfold\\_cv} in \\texttt{scripts/augmentation\\_experiment.py} and "
      "\\texttt{scripts/discrimination\\_experiments.py}; and the training seeds (0, 1, 2) are "
      "passed with \\texttt{--seed} to \\texttt{scripts/discrimination\\_experiments.py}. "
      "Two parameters in the file, \\texttt{test\\_size} and \\texttt{decision\\_threshold}, "
      "are commented out because the pipeline does not use them: evaluation is by "
      "cross-validation, and predictions are made by argmax. "
      "Reproducing the dataset requires this file, the event directories it names, and the "
      "fixed seed it specifies.\\par}")
    w("")
    w("\\begin{footnotesize}")
    w("\\begin{verbatim}")
    for line in CONFIG.read_text().rstrip("\n").split("\n"):
        L.append(line)
    w("\\end{verbatim}")
    w("\\end{footnotesize}")
    w("")
    w("\\section{Software environment}")
    w("")
    w("Results were produced with PyTorch 2.5.1 and scikit-learn 1.9.0 under "
      "Python 3.11, on the CPU backend. The full environment specification is "
      "given below.")
    w("")
    w("\\begin{footnotesize}")
    w("\\begin{verbatim}")
    L.extend(ENV.read_text().rstrip("\n").split("\n"))
    w("\\end{verbatim}")
    w("\\end{footnotesize}")
    w("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
